<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MatchingEngine.Domain\MatchingEngine.Domain.csproj" />
    <ProjectReference Include="..\MatchingEngine.Core\MatchingEngine.Core.csproj" />
  </ItemGroup>

</Project>
